"""
This type stub file was generated by pyright.
"""

from .calibrate import CalibraterBase, CalibrationDataReader, CalibrationMethod, MinMaxCalibrater, create_calibrator
from .qdq_quantizer import QDQQuantizer
from .quant_utils import QuantFormat, QuantType, write_calibration_table
from .quantize import DynamicQuantConfig, QuantizationMode, StaticQuantConfig, get_qdq_config, quantize, quantize_dynamic, quantize_static
from .shape_inference import quant_pre_process

