# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

"""
Centralized types module for CodeWeaver.

This module provides a single import point for all commonly used types,
classes, and functions from the _types subpackage, eliminating circular
dependency issues and simplifying import statements.
"""

from codeweaver.types.backends import (
    BACKEND_PROVIDER_REGISTRY,
    BackendProvider,
    CollectionInfo,
    DistanceMetric,
    EmbeddingProviderBase,
    FilterCondition,
    FilterOperator,
    HybridFusionStrategy,
    HybridStrategy,
    IndexType,
    ProviderInfo,
    RerankProviderBase,
    SearchFilter,
    SearchResult,
    SparseIndexType,
    StorageType,
    VectorPoint,
)
from codeweaver.types.base_enum import BaseEnum

# Configuration types
from codeweaver.types.config import (
    BaseComponentConfig,
    ComponentType,
    ConfigFormat,
    ConfigurationError,
    ServiceType,
)

# Content models
from codeweaver.types.content import CodeChunk, ContentSearchResult

# Enums
from codeweaver.types.enums import (
    ChunkingStrategy,
    ComponentState,
    ErrorCategory,
    ErrorSeverity,
    Language,
    PerformanceMode,
    SearchComplexity,
)

# Exception types
from codeweaver.types.exceptions import (
    BackendAuthError,
    BackendCollectionNotFoundError,
    BackendConnectionError,
    BackendError,
    BackendUnsupportedOperationError,
    BackendVectorDimensionMismatchError,
    CodeWeaverError,
    CodeWeaverFactoryError,
    ComponentCreationError,
    ComponentNotFoundError,
    ComponentUnavailableError,
    PluginError,
    RegistrationError,
    ValidationError,
)

# Factories and data structures
from codeweaver.types.factories import (
    BaseCapabilities,
    BaseComponentInfo,
    CapabilityQueryMixin,
    ComponentInstances,
    ComponentLifecycle,
    ComponentRegistration,
    ComponentRegistry,
    ContentItem,
    CreationResult,
    DimensionSize,
    ExtensibilityConfig,
    InitializationContext,
    InitializationResult,
    PluginInfo,
    ProviderRegistration,
    RegistrationResult,
    T,
    ValidationResult,
)

# Provider capabilities and registry
# Provider types from providers module
from codeweaver.types.providers import (
    PROVIDER_REGISTRY,
    CohereModels,
    CohereRerankModels,
    EmbeddingProviderInfo,
    ModelFamily,
    OpenAIModels,
    ProviderCapability,
    ProviderKind,
    ProviderRegistryEntry,
    ProviderType,
    RerankResult,
    VoyageModels,
    VoyageRerankModels,
    get_available_providers,
    get_provider_registry_entry,
    register_provider_class,
)
from codeweaver.types.services import (
    AccessDeniedError,
    CacheError,
    CacheServiceConfig,
    CacheStats,
    ChunkingError,
    ChunkingServiceConfig,
    ChunkingStats,
    DependencyInjectionError,
    DependencyResolutionError,
    DirectoryNotFoundError,
    DirectoryStats,
    DuplicateProviderError,
    ErrorHandlingServiceConfig,
    FileMetadata,
    FilteringError,
    FilteringServiceConfig,
    FilteringStats,
    HealthStatus,
    LoggingServiceConfig,
    MetricsServiceConfig,
    MonitoringServiceConfig,
    ProviderNotFoundError,
    ProviderRegistrationError,
    ProviderStatus,
    RateLimitingServiceConfig,
    ReconfigurationError,
    ServiceCapabilities,
    ServiceConfig,
    ServiceConfigurationError,
    ServiceCreationError,
    ServiceError,
    ServiceHealth,
    ServiceHealthReport,
    ServiceInitializationError,
    ServiceInstanceInfo,
    ServiceNotFoundError,
    ServiceNotReadyError,
    ServiceProviderInfo,
    ServiceRegistryHealth,
    ServiceRestartError,
    ServicesConfig,
    ServiceStartError,
    ServiceStopError,
    TimingServiceConfig,
    UnsupportedLanguageError,
    ValidationErrorData,
    ValidationLevel,
    ValidationRule,
    ValidationServiceConfig,
    ValidationSeverity,
    ValidationStats,
    ValidationWarning,
)
from codeweaver.types.sources import (
    SOURCE_PROVIDERS,
    APIType,
    AuthType,
    ContentType,
    DatabaseType,
    SourceCapabilities,
    SourceCapability,
    SourceProvider,
    SourceProviderInfo,
)


__all_backend_types__ = (
    "BACKEND_PROVIDER_REGISTRY",
    "BackendCapabilities",
    "BackendProvider",
    "CollectionInfo",
    "DistanceMetric",
    "EmbeddingProviderBase",
    "FilterCondition",
    "FilterOperator",
    "HybridFusionStrategy",
    "HybridStrategy",
    "IndexType",
    "ProviderInfo",
    "RerankProviderBase",
    "SearchFilter",
    "SearchResult",
    "SparseIndexType",
    "StorageType",
    "VectorPoint",
)

__all_exception_types__ = (
    "BackendAuthError",
    "BackendCollectionNotFoundError",
    "BackendConnectionError",
    "BackendError",
    "BackendUnsupportedOperationError",
    "BackendVectorDimensionMismatchError",
    "CodeWeaverError",
    "CodeWeaverFactoryError",
    "ComponentCreationError",
    "ComponentNotFoundError",
    "ComponentUnavailableError",
    "PluginError",
    "RegistrationError",
    "ValidationError",
)

__all_factory_types__ = (
    "ComponentInstances",
    "ComponentLifecycle",
    "ContentItem",
    "ExtensibilityConfig",
    "InitializationContext",
    "InitializationResult",
    "PluginInfo",
    "ProviderRegistration",
    "BaseCapabilities",
    "BaseComponentInfo",
    "CapabilityQueryMixin",
    "ComponentRegistration",
    "ComponentRegistry",
    "CreationResult",
    "DimensionSize",
    "RegistrationResult",
    "T",
    "ValidationResult",
)

__all_provider_types__ = (
    "PROVIDER_REGISTRY",
    "CohereModels",
    "CohereRerankModels",
    "EmbeddingProviderInfo",
    "ModelFamily",
    "OpenAIModels",
    "ProviderCapabilities",
    "ProviderCapability",
    "ProviderKind",
    "ProviderRegistryEntry",
    "ProviderType",
    "RerankResult",
    "VoyageModels",
    "VoyageRerankModels",
    "get_available_providers",
    "get_provider_registry_entry",
    "register_provider_class",
)

__all_service_types__ = (
    "CacheServiceConfig",
    "CacheStats",
    "ChunkingServiceConfig",
    "ChunkingStats",
    "DirectoryStats",
    "ErrorHandlingServiceConfig",
    "FileMetadata",
    "FilteringServiceConfig",
    "FilteringStats",
    "HealthStatus",
    "LoggingServiceConfig",
    "MetricsServiceConfig",
    "MonitoringServiceConfig",
    "ProviderStatus",
    "RateLimitingServiceConfig",
    "ServiceCapabilities",
    "ServiceConfig",
    "ServiceHealth",
    "ServiceHealthReport",
    "ServiceInstanceInfo",
    "ServiceProviderInfo",
    "ServiceRegistryHealth",
    "ServicesConfig",
    "TimingServiceConfig",
    "ValidationError",
    "ValidationLevel",
    "ValidationRule",
    "ValidationServiceConfig",
    "ValidationSeverity",
    "ValidationStats",
    "ValidationWarning",
)

__all_source_types__ = [
    "SOURCE_PROVIDERS",
    "APIType",
    "AuthType",
    "ContentType",
    "DatabaseType",
    "SourceCapabilities",
    "SourceCapability",
    "SourceProvider",
    "SourceProviderInfo",
]

__all__ = (
    "BACKEND_PROVIDER_REGISTRY",
    "PROVIDER_REGISTRY",
    "SOURCE_PROVIDERS",
    "APIType",
    "AccessDeniedError",
    "AuthType",
    "BackendAuthError",
    "BackendCollectionNotFoundError",
    "BackendConnectionError",
    "BackendError",
    "BackendProvider",
    "BackendUnsupportedOperationError",
    "BackendVectorDimensionMismatchError",
    "BaseCapabilities",
    "BaseComponentConfig",
    "BaseComponentInfo",
    "BaseEnum",
    "CacheError",
    "CacheServiceConfig",
    "CacheStats",
    "CapabilityQueryMixin",
    "ChunkingError",
    "ChunkingServiceConfig",
    "ChunkingStats",
    "ChunkingStrategy",
    "CodeChunk",
    "CodeWeaverError",
    "CodeWeaverFactoryError",
    "CohereModels",
    "CohereRerankModels",
    "CollectionInfo",
    "ComponentCreationError",
    "ComponentInstances",
    "ComponentLifecycle",
    "ComponentNotFoundError",
    "ComponentRegistration",
    "ComponentRegistry",
    "ComponentState",
    "ComponentType",
    "ComponentUnavailableError",
    "ConfigFormat",
    "ConfigurationError",
    "ContentItem",
    "ContentSearchResult",
    "ContentType",
    "CreationResult",
    "DatabaseType",
    "DependencyInjectionError",
    "DependencyResolutionError",
    "DimensionSize",
    "DirectoryNotFoundError",
    "DirectoryStats",
    "DistanceMetric",
    "DuplicateProviderError",
    "EmbeddingProviderBase",
    "EmbeddingProviderInfo",
    "ErrorCategory",
    "ErrorHandlingServiceConfig",
    "ErrorSeverity",
    "ExtensibilityConfig",
    "FileMetadata",
    "FilterCondition",
    "FilterOperator",
    "FilteringError",
    "FilteringServiceConfig",
    "FilteringStats",
    "HealthStatus",
    "HybridFusionStrategy",
    "HybridStrategy",
    "IndexType",
    "InitializationContext",
    "InitializationResult",
    "Language",
    "LoggingServiceConfig",
    "MetricsServiceConfig",
    "ModelFamily",
    "MonitoringServiceConfig",
    "OpenAIModels",
    "PerformanceMode",
    "PluginError",
    "PluginInfo",
    "ProviderCapability",
    "ProviderInfo",
    "ProviderKind",
    "ProviderNotFoundError",
    "ProviderRegistration",
    "ProviderRegistrationError",
    "ProviderRegistryEntry",
    "ProviderStatus",
    "ProviderType",
    "RateLimitingServiceConfig",
    "ReconfigurationError",
    "RegistrationError",
    "RegistrationResult",
    "RerankProviderBase",
    "RerankResult",
    "SearchComplexity",
    "SearchFilter",
    "SearchResult",
    "ServiceCapabilities",
    "ServiceConfig",
    "ServiceConfigurationError",
    "ServiceCreationError",
    "ServiceError",
    "ServiceHealth",
    "ServiceHealthReport",
    "ServiceInitializationError",
    "ServiceInstanceInfo",
    "ServiceNotFoundError",
    "ServiceNotReadyError",
    "ServiceProviderInfo",
    "ServiceRegistryHealth",
    "ServiceRestartError",
    "ServiceStartError",
    "ServiceStopError",
    "ServiceType",
    "ServicesConfig",
    "SourceCapabilities",
    "SourceCapability",
    "SourceProvider",
    "SourceProviderInfo",
    "SparseIndexType",
    "StorageType",
    "T",
    "TimingServiceConfig",
    "UnsupportedLanguageError",
    "ValidationError",
    "ValidationErrorData",
    "ValidationLevel",
    "ValidationResult",
    "ValidationRule",
    "ValidationServiceConfig",
    "ValidationSeverity",
    "ValidationStats",
    "ValidationWarning",
    "VectorPoint",
    "VoyageModels",
    "VoyageRerankModels",
    "get_available_providers",
    "get_provider_registry_entry",
    "register_provider_class",
)
