"""
This type stub file was generated by pyright.
"""

from collections.abc import Awaitable, Callable
from typing import Any, Generic, TypeAlias, TypeVar
from mcp import ClientSession
from mcp.client.session import ElicitationFnT
from mcp.shared.context import LifespanContextT, RequestContext
from mcp.types import ElicitRequestParams, ElicitResult as MCPElicitResult

__all__ = ['ElicitRequestParams', 'ElicitResult', 'ElicitationHandler']
T = TypeVar('T')
class ElicitResult(MCPElicitResult, Generic[T]):
    content: T | None = ...


ElicitationHandler: TypeAlias = Callable[[str, type[T], ElicitRequestParams, RequestContext[ClientSession, LifespanContextT]], Awaitable[T | dict[str, Any] | ElicitResult[T | dict[str, Any]]]]
def create_elicitation_callback(elicitation_handler: ElicitationHandler) -> ElicitationFnT:
    ...

