"""
This type stub file was generated by pyright.
"""

import mcp.types
from collections.abc import Awaitable, Callable
from typing import TypeAlias
from mcp import ClientSession
from mcp.client.session import ListRootsFnT
from mcp.shared.context import LifespanContextT, RequestContext

RootsList: TypeAlias = list[str] | list[mcp.types.Root] | list[str | mcp.types.Root]
RootsHandler: TypeAlias = Callable[[RequestContext[ClientSession, LifespanContextT]], RootsList] | Callable[[RequestContext[ClientSession, LifespanContextT]], Awaitable[RootsList]]
def convert_roots_list(roots: RootsList) -> list[mcp.types.Root]:
    ...

def create_roots_callback(handler: RootsList | RootsHandler) -> ListRootsFnT:
    ...

