"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from enum import Enum
from typing import Any, Optional

@dataclass(frozen=True)
class ModelSource:
    hf: Optional[str] = ...
    url: Optional[str] = ...
    _deprecated_tar_struct: bool = ...
    @property
    def deprecated_tar_struct(self) -> bool:
        ...
    
    def __post_init__(self) -> None:
        ...
    


@dataclass(frozen=True)
class BaseModelDescription:
    model: str
    sources: ModelSource
    model_file: str
    description: str
    license: str
    size_in_GB: float
    additional_files: list[str] = ...


@dataclass(frozen=True)
class DenseModelDescription(BaseModelDescription):
    dim: Optional[int] = ...
    tasks: Optional[dict[str, Any]] = ...
    def __post_init__(self) -> None:
        ...
    


@dataclass(frozen=True)
class SparseModelDescription(BaseModelDescription):
    requires_idf: Optional[bool] = ...
    vocab_size: Optional[int] = ...


class PoolingType(str, Enum):
    CLS = ...
    MEAN = ...
    DISABLED = ...


