"""
This type stub file was generated by pyright.
"""

import numpy as np
from dataclasses import dataclass
from typing import Any, Generic, Iterable, Optional, TypeVar
from numpy.typing import NDArray
from fastembed.common.types import NumpyArray
from fastembed.parallel_processor import Worker

T = TypeVar("T")
@dataclass
class OnnxOutputContext:
    model_output: NumpyArray
    attention_mask: Optional[NDArray[np.int64]] = ...
    input_ids: Optional[NDArray[np.int64]] = ...


class OnnxModel(Generic[T]):
    def __init__(self) -> None:
        ...
    
    def load_onnx_model(self) -> None:
        ...
    
    def onnx_embed(self, *args: Any, **kwargs: Any) -> OnnxOutputContext:
        ...
    


class EmbeddingWorker(Worker, Generic[T]):
    def init_embedding(self, model_name: str, cache_dir: str, **kwargs: Any) -> OnnxModel[T]:
        ...
    
    def __init__(self, model_name: str, cache_dir: str, **kwargs: Any) -> None:
        ...
    
    @classmethod
    def start(cls, model_name: str, cache_dir: str, **kwargs: Any) -> EmbeddingWorker[T]:
        ...
    
    def process(self, items: Iterable[tuple[int, Any]]) -> Iterable[tuple[int, Any]]:
        ...
    


