"""
This type stub file was generated by pyright.
"""

import sys
import numpy as np
from pathlib import Path
from PIL import Image
from typing import Any, TypeAlias, Union
from numpy.typing import NDArray

if sys.version_info >= (3, 10):
    ...
else:
    ...
PathInput: TypeAlias = Union[str, Path]
ImageInput: TypeAlias = Union[PathInput, Image.Image]
OnnxProvider: TypeAlias = Union[str, tuple[str, dict[Any, Any]]]
NumpyArray = Union[NDArray[np.float64], NDArray[np.float32], NDArray[np.float16], NDArray[np.int8], NDArray[np.int64], NDArray[np.int32],]
