"""
This type stub file was generated by pyright.
"""

import numpy as np
from pathlib import Path
from typing import Iterable, Optional, TypeVar
from numpy.typing import NDArray
from fastembed.common.types import NumpyArray

T = TypeVar("T")
def normalize(input_array: NumpyArray, p: int = ..., dim: int = ..., eps: float = ...) -> NumpyArray:
    ...

def mean_pooling(input_array: NumpyArray, attention_mask: NDArray[np.int64]) -> NumpyArray:
    ...

def iter_batch(iterable: Iterable[T], size: int) -> Iterable[list[T]]:
    """
    >>> list(iter_batch([1,2,3,4,5], 3))
    [[1, 2, 3], [4, 5]]
    """
    ...

def define_cache_dir(cache_dir: Optional[str] = ...) -> Path:
    """
    Define the cache directory for fastembed
    """
    ...

def get_all_punctuation() -> set[str]:
    ...

def remove_non_alphanumeric(text: str) -> str:
    ...

