"""
This type stub file was generated by pyright.
"""

from typing import Union
from PIL import Image
from fastembed.common.types import NumpyArray

def convert_to_rgb(image: Image.Image) -> Image.Image:
    ...

def center_crop(image: Union[Image.Image, NumpyArray], size: tuple[int, int]) -> NumpyArray:
    ...

def normalize(image: NumpyArray, mean: Union[float, list[float]], std: Union[float, list[float]]) -> NumpyArray:
    ...

def resize(image: Image.Image, size: Union[int, tuple[int, int]], resample: Union[int, Image.Resampling] = ...) -> Image.Image:
    ...

def rescale(image: NumpyArray, scale: float, dtype: type = ...) -> NumpyArray:
    ...

def pil2ndarray(image: Union[Image.Image, NumpyArray]) -> NumpyArray:
    ...

def pad2square(image: Image.Image, size: int, fill_color: Union[str, int, tuple[int, ...]] = ...) -> Image.Image:
    ...

