"""
This type stub file was generated by pyright.
"""

from typing import Any, Union
from PIL import Image
from fastembed.common.types import NumpyArray

class Transform:
    def __call__(self, images: list[Any]) -> Union[list[Image.Image], list[NumpyArray]]:
        ...
    


class ConvertToRGB(Transform):
    def __call__(self, images: list[Image.Image]) -> list[Image.Image]:
        ...
    


class CenterCrop(Transform):
    def __init__(self, size: tuple[int, int]) -> None:
        ...
    
    def __call__(self, images: list[Image.Image]) -> list[NumpyArray]:
        ...
    


class Normalize(Transform):
    def __init__(self, mean: Union[float, list[float]], std: Union[float, list[float]]) -> None:
        ...
    
    def __call__(self, images: list[NumpyArray]) -> list[NumpyArray]:
        ...
    


class Resize(Transform):
    def __init__(self, size: Union[int, tuple[int, int]], resample: Image.Resampling = ...) -> None:
        ...
    
    def __call__(self, images: list[Image.Image]) -> list[Image.Image]:
        ...
    


class Rescale(Transform):
    def __init__(self, scale: float = ...) -> None:
        ...
    
    def __call__(self, images: list[NumpyArray]) -> list[NumpyArray]:
        ...
    


class PILtoNDarray(Transform):
    def __call__(self, images: list[Union[Image.Image, NumpyArray]]) -> list[NumpyArray]:
        ...
    


class PadtoSquare(Transform):
    def __init__(self, size: int, fill_color: Union[str, int, tuple[int, ...]]) -> None:
        ...
    
    def __call__(self, images: list[Image.Image]) -> list[Image.Image]:
        ...
    


class Compose:
    def __init__(self, transforms: list[Transform]) -> None:
        ...
    
    def __call__(self, images: Union[list[Image.Image], list[NumpyArray]]) -> Union[list[NumpyArray], list[Image.Image]]:
        ...
    
    @classmethod
    def from_config(cls, config: dict[str, Any]) -> Compose:
        """Creates processor from a config dict.
        Args:
            config (dict[str, Any]): Configuration dictionary.

                Valid keys:
                    - do_resize
                    - resize_mode
                    - size
                    - fill_color
                    - do_center_crop
                    - crop_size
                    - do_rescale
                    - rescale_factor
                    - do_normalize
                    - image_mean
                    - mean
                    - image_std
                    - std
                    - resample
                    - interpolation
                Valid size keys (nested):
                    - {"height", "width"}
                    - {"shortest_edge"}

        Returns:
            Compose: Image processor.
        """
        ...
    


