"""
This type stub file was generated by pyright.
"""

import httpx

__all__ = ["BearerAuth"]
logger = ...
class BearerAuth(httpx.Auth):
    def __init__(self, token: str) -> None:
        ...
    
    def auth_flow(self, request): # -> Generator[Request, Any, None]:
        ...
    


