"""
This type stub file was generated by pyright.
"""

class MachineInfo:
    """Class encapsulating Machine Info logic."""
    def __init__(self, silent=..., logger=...) -> None:
        ...
    
    def get_machine_info(self): # -> dict[str, dict[Any, Any] | str | list[str]]:
        """Get machine info in metric format"""
        ...
    
    def get_memory_info(self) -> dict:
        """Get memory info"""
        ...
    
    def get_cpu_info(self) -> dict:
        """Get CPU info"""
        ...
    
    def get_gpu_info_by_nvml(self) -> dict:
        """Get GPU info using nvml"""
        ...
    
    def get_related_packages(self) -> list[str]:
        ...
    
    def get_onnxruntime_info(self) -> dict:
        ...
    
    def get_pytorch_info(self) -> dict:
        ...
    
    def get_tensorflow_info(self) -> dict:
        ...
    


def parse_arguments(): # -> Namespace:
    ...

def get_machine_info(silent=...) -> str:
    ...

def get_device_info(silent=...) -> str:
    ...

if __name__ == "__main__":
    args = ...
