"""
This type stub file was generated by pyright.
"""

from onnx import ModelProto

def extract_raw_data_from_model(model: ModelProto): # -> zip[tuple[Any, ...]]:
    """
    Extract external data from model and return the external data as a list of tuples (name, value).
    Note this function does not handle external data that is not loaded into the model as raw data.

    Args:
        model (ModelProto): the model proto to extract external data from.
    Returns:
        (external_names, external_values): a tuple of two lists of external data names and values.
    """
    ...

def has_external_data(model: ModelProto): # -> bool:
    """
    Check if the model has external data.

    Args:
        model (ModelProto): the model proto to check for external data.
    Returns:
        bool: True if the model has external data, False otherwise.
    """
    ...

