"""
This type stub file was generated by pyright.
"""

import warnings
import fastmcp.server
from importlib.metadata import version as _version
from fastmcp.settings import Settings
from fastmcp.utilities.logging import configure_logging as _configure_logging
from fastmcp.server.server import FastMCP
from fastmcp.server.context import Context
from fastmcp.client import Client
from . import client

"""FastMCP - An ergonomic MCP interface."""
settings = ...
__version__ = ...
if settings.deprecation_warnings:
    ...
def __getattr__(name: str): # -> type[Image]:
    """
    Used to deprecate the module-level Image class; can be removed once it is no longer imported to root.
    """
    ...

__all__ = ["FastMCP", "Context", "client", "Client", "settings"]
