"""
This type stub file was generated by pyright.
"""

from typing import Any
from fastembed.text.onnx_embedding import OnnxTextEmbedding, OnnxTextEmbeddingWorker
from fastembed.common.model_description import DenseModelDescription

supported_clip_models: list[DenseModelDescription] = ...
class CLIPOnnxEmbedding(OnnxTextEmbedding):
    ...


class CLIPEmbeddingWorker(OnnxTextEmbeddingWorker):
    def init_embedding(self, model_name: str, cache_dir: str, **kwargs: Any) -> OnnxTextEmbedding:
        ...
    


