"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional, Sequence
from dataclasses import dataclass
from fastembed.common import OnnxProvider
from fastembed.common.model_description import DenseModelDescription, PoolingType
from fastembed.text.onnx_embedding import OnnxTextEmbedding

@dataclass(frozen=True)
class PostprocessingConfig:
    pooling: PoolingType
    normalization: bool
    ...


class CustomTextEmbedding(OnnxTextEmbedding):
    SUPPORTED_MODELS: list[DenseModelDescription] = ...
    POSTPROCESSING_MAPPING: dict[str, PostprocessingConfig] = ...
    def __init__(self, model_name: str, cache_dir: Optional[str] = ..., threads: Optional[int] = ..., providers: Optional[Sequence[OnnxProvider]] = ..., cuda: bool = ..., device_ids: Optional[list[int]] = ..., lazy_load: bool = ..., device_id: Optional[int] = ..., specific_model_path: Optional[str] = ..., **kwargs: Any) -> None:
        ...
    
    @classmethod
    def add_model(cls, model_description: DenseModelDescription, pooling: PoolingType, normalization: bool) -> None:
        ...
    


