"""
This type stub file was generated by pyright.
"""

from enum import Enum
from typing import Any, Iterable, Optional, Union
from fastembed.common.onnx_model import OnnxOutputContext
from fastembed.common.types import NumpyArray
from fastembed.text.pooled_normalized_embedding import PooledNormalizedEmbedding
from fastembed.text.onnx_embedding import OnnxTextEmbeddingWorker
from fastembed.common.model_description import DenseModelDescription

supported_multitask_models: list[DenseModelDescription] = ...
class Task(int, Enum):
    RETRIEVAL_QUERY = ...
    RETRIEVAL_PASSAGE = ...
    SEPARATION = ...
    CLASSIFICATION = ...
    TEXT_MATCHING = ...


class JinaEmbeddingV3(PooledNormalizedEmbedding):
    PASSAGE_TASK = ...
    QUERY_TASK = ...
    def __init__(self, *args: Any, task_id: Optional[int] = ..., **kwargs: Any) -> None:
        ...
    
    def embed(self, documents: Union[str, Iterable[str]], batch_size: int = ..., parallel: Optional[int] = ..., task_id: Optional[int] = ..., **kwargs: Any) -> Iterable[NumpyArray]:
        ...
    
    def query_embed(self, query: Union[str, Iterable[str]], **kwargs: Any) -> Iterable[NumpyArray]:
        ...
    
    def passage_embed(self, texts: Iterable[str], **kwargs: Any) -> Iterable[NumpyArray]:
        ...
    


class JinaEmbeddingV3Worker(OnnxTextEmbeddingWorker):
    def init_embedding(self, model_name: str, cache_dir: str, **kwargs: Any) -> JinaEmbeddingV3:
        ...
    
    def process(self, items: Iterable[tuple[int, Any]]) -> Iterable[tuple[int, OnnxOutputContext]]:
        ...
    


