"""
This type stub file was generated by pyright.
"""

from typing import Any, Iterable, Optional
from tokenizers import Encoding
from fastembed.common.onnx_model import EmbeddingWorker, OnnxModel, OnnxOutputContext, T

class OnnxTextModel(OnnxModel[T]):
    ONNX_OUTPUT_NAMES: Optional[list[str]] = ...
    def __init__(self) -> None:
        ...
    
    def load_onnx_model(self) -> None:
        ...
    
    def tokenize(self, documents: list[str], **kwargs: Any) -> list[Encoding]:
        ...
    
    def onnx_embed(self, documents: list[str], **kwargs: Any) -> OnnxOutputContext:
        ...
    


class TextEmbeddingWorker(EmbeddingWorker[T]):
    def process(self, items: Iterable[tuple[int, Any]]) -> Iterable[tuple[int, OnnxOutputContext]]:
        ...
    


