"""
This type stub file was generated by pyright.
"""

import numpy as np
from typing import Any
from numpy.typing import NDArray
from fastembed.common.types import NumpyArray
from fastembed.text.onnx_embedding import OnnxTextEmbedding, OnnxTextEmbeddingWorker
from fastembed.common.model_description import DenseModelDescription

supported_pooled_models: list[DenseModelDescription] = ...
class PooledEmbedding(OnnxTextEmbedding):
    @classmethod
    def mean_pooling(cls, model_output: NumpyArray, attention_mask: NDArray[np.int64]) -> NumpyArray:
        ...
    


class PooledEmbeddingWorker(OnnxTextEmbeddingWorker):
    def init_embedding(self, model_name: str, cache_dir: str, **kwargs: Any) -> OnnxTextEmbedding:
        ...
    


