"""
This type stub file was generated by pyright.
"""

from typing import Any
from fastembed.text.onnx_embedding import OnnxTextEmbedding, OnnxTextEmbeddingWorker
from fastembed.text.pooled_embedding import PooledEmbedding
from fastembed.common.model_description import DenseModelDescription

supported_pooled_normalized_models: list[DenseModelDescription] = ...
class PooledNormalizedEmbedding(PooledEmbedding):
    ...


class PooledNormalizedEmbeddingWorker(OnnxTextEmbeddingWorker):
    def init_embedding(self, model_name: str, cache_dir: str, **kwargs: Any) -> OnnxTextEmbedding:
        ...
    


