"""
This type stub file was generated by pyright.
"""

import datetime
from typing import Any

UTC = ...
class TimedCache:
    NOT_FOUND = ...
    def __init__(self, expiration: datetime.timedelta) -> None:
        ...
    
    def set(self, key: Any, value: Any) -> None:
        ...
    
    def get(self, key: Any) -> Any:
        ...
    
    def clear(self) -> None:
        ...
    


