"""
This type stub file was generated by pyright.
"""

from typing import Any, Literal, TYPE_CHECKING
from fastmcp import FastMCP

if TYPE_CHECKING:
    ...
LOGO_ASCII = ...
def log_server_banner(server: FastMCP[Any], transport: Literal["stdio", "http", "sse", "streamable-http"], *, host: str | None = ..., port: int | None = ..., path: str | None = ...) -> None:
    """Creates and logs a formatted banner with server information and logo.

    Args:
        transport: The transport protocol being used
        server_name: Optional server name to display
        host: Host address (for HTTP transports)
        port: Port number (for HTTP transports)
        path: Server path (for HTTP transports)
    """
    ...

