"""
This type stub file was generated by pyright.
"""

def compress_schema(schema: dict, prune_params: list[str] | None = ..., prune_defs: bool = ..., prune_additional_properties: bool = ..., prune_titles: bool = ...) -> dict:
    """
    Remove the given parameters from the schema.

    Args:
        schema: The schema to compress
        prune_params: List of parameter names to remove from properties
        prune_defs: Whether to remove unused definitions
        prune_additional_properties: Whether to remove additionalProperties: false
        prune_titles: Whether to remove title fields from the schema
    """
    ...

