"""
This type stub file was generated by pyright.
"""

import logging
from typing import Literal

"""Logging utilities for FastMCP."""
def get_logger(name: str) -> logging.Logger:
    """Get a logger nested under FastMCP namespace.

    Args:
        name: the name of the logger, which will be prefixed with 'FastMCP.'

    Returns:
        a configured logger instance
    """
    ...

def configure_logging(level: Literal["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"] | int = ..., logger: logging.Logger | None = ..., enable_rich_tracebacks: bool = ...) -> None:
    """
    Configure logging for FastMCP.

    Args:
        logger: the logger to configure
        level: the log level to use
    """
    ...

