"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional, Sequence
from fastembed.common import OnnxProvider
from fastembed.common.model_description import BaseModelDescription
from fastembed.rerank.cross_encoder.onnx_text_cross_encoder import OnnxTextCrossEncoder

class CustomTextCrossEncoder(OnnxTextCrossEncoder):
    SUPPORTED_MODELS: list[BaseModelDescription] = ...
    def __init__(self, model_name: str, cache_dir: Optional[str] = ..., threads: Optional[int] = ..., providers: Optional[Sequence[OnnxProvider]] = ..., cuda: bool = ..., device_ids: Optional[list[int]] = ..., lazy_load: bool = ..., device_id: Optional[int] = ..., specific_model_path: Optional[str] = ..., **kwargs: Any) -> None:
        ...
    
    @classmethod
    def add_model(cls, model_description: BaseModelDescription) -> None:
        ...
    


