"""
This type stub file was generated by pyright.
"""

from typing import Any, Iterable, Optional
from tokenizers import Encoding
from fastembed.common.onnx_model import EmbeddingWorker, OnnxModel, OnnxOutputContext

class OnnxCrossEncoderModel(OnnxModel[float]):
    ONNX_OUTPUT_NAMES: Optional[list[str]] = ...
    def tokenize(self, pairs: list[tuple[str, str]], **_: Any) -> list[Encoding]:
        ...
    
    def onnx_embed(self, query: str, documents: list[str], **kwargs: Any) -> OnnxOutputContext:
        ...
    
    def onnx_embed_pairs(self, pairs: list[tuple[str, str]], **kwargs: Any) -> OnnxOutputContext:
        ...
    


class TextRerankerWorker(EmbeddingWorker[float]):
    def __init__(self, model_name: str, cache_dir: str, **kwargs: Any) -> None:
        ...
    
    def init_embedding(self, model_name: str, cache_dir: str, **kwargs: Any) -> OnnxCrossEncoderModel:
        ...
    
    def process(self, items: Iterable[tuple[int, Any]]) -> Iterable[tuple[int, Any]]:
        ...
    


