"""
This type stub file was generated by pyright.
"""

from .base_operator import QuantOperatorBase

class QLinearBinaryOp(QuantOperatorBase):
    def __init__(self, onnx_quantizer, onnx_node) -> None:
        ...
    
    def quantize(self): # -> None:
        ...
    


