"""
This type stub file was generated by pyright.
"""

from .base_operator import QuantOperatorBase
from .qdq_base_operator import QDQOperatorBase

class GatherQuant(QuantOperatorBase):
    def __init__(self, onnx_quantizer, onnx_node) -> None:
        ...
    
    def should_quantize(self): # -> Literal[False]:
        ...
    
    def quantize(self): # -> None:
        ...
    


class QDQGather(QDQOperatorBase):
    def __init__(self, onnx_quantizer, onnx_node) -> None:
        ...
    
    def quantize(self): # -> None:
        ...
    


