"""
This type stub file was generated by pyright.
"""

from .matmul import QOpMatMul
from .qdq_base_operator import QDQOperatorBase

def is_B_transposed(gemm_node): # -> Literal[False]:
    ...

def get_beta(gemm_node): # -> float:
    ...

def set_default_beta(gemm_node): # -> float:
    ...

class QLinearGemm(QOpMatMul):
    def __init__(self, onnx_quantizer, onnx_node) -> None:
        ...
    
    def quantize(self): # -> None:
        ...
    


class QDQGemm(QDQOperatorBase):
    def __init__(self, onnx_quantizer, onnx_node) -> None:
        ...
    
    def quantize(self): # -> None:
        ...
    


