"""
This type stub file was generated by pyright.
"""

from .base_operator import QuantOperatorBase
from .qdq_base_operator import QDQOperatorBase

class QOpMatMul(QuantOperatorBase):
    def __init__(self, onnx_quantizer, onnx_node) -> None:
        ...
    
    def should_quantize(self): # -> bool:
        ...
    


class MatMulInteger(QOpMatMul):
    def __init__(self, onnx_quantizer, onnx_node) -> None:
        ...
    
    def quantize(self): # -> None:
        ...
    


class QLinearMatMul(QOpMatMul):
    def __init__(self, onnx_quantizer, onnx_node) -> None:
        ...
    
    def quantize(self): # -> None:
        ...
    


class QDQMatMul(QDQOperatorBase):
    def __init__(self, onnx_quantizer, onnx_node) -> None:
        ...
    
    def quantize(self): # -> None:
        ...
    


