"""
This type stub file was generated by pyright.
"""

from .qdq_base_operator import QDQOperatorBase

class QDQNormalization(QDQOperatorBase):
    def __init__(self, onnx_quantizer, onnx_node) -> None:
        ...
    
    def quantize(self): # -> None:
        ...
    


