"""
This type stub file was generated by pyright.
"""

from .base_operator import QuantOperatorBase
from .qdq_base_operator import QDQOperatorBase

class QPad(QuantOperatorBase):
    def __init__(self, onnx_quantizer, onnx_node) -> None:
        ...
    
    def quantize(self): # -> None:
        ...
    


class QDQPad(QDQOperatorBase):
    def __init__(self, onnx_quantizer, onnx_node) -> None:
        ...
    
    def quantize(self): # -> None:
        ...
    


