"""
This type stub file was generated by pyright.
"""

class QDQOperatorBase:
    def __init__(self, onnx_quantizer, onnx_node) -> None:
        ...
    
    def quantize(self): # -> None:
        ...
    


