"""
This type stub file was generated by pyright.
"""

from .base_operator import QuantOperatorBase
from .qdq_base_operator import QDQOperatorBase

class QLinearWhere(QuantOperatorBase):
    def should_quantize(self): # -> Literal[True]:
        ...
    
    def quantize(self): # -> None:
        ...
    


class QDQWhere(QDQOperatorBase):
    def quantize(self): # -> None:
        ...
    


