"""
This type stub file was generated by pyright.
"""

np = ...
class KeyValue:
    __slots__ = ...
    @classmethod
    def GetRootAs(cls, buf, offset=...): # -> KeyValue:
        ...
    
    @classmethod
    def GetRootAsKeyValue(cls, buf, offset=...): # -> KeyValue:
        """This method is deprecated. Please switch to GetRootAs."""
        ...
    
    def Init(self, buf, pos): # -> None:
        ...
    
    def Key(self): # -> bytes | None:
        ...
    
    def Value(self): # -> bytes | None:
        ...
    


def Start(builder): # -> None:
    ...

def KeyValueStart(builder): # -> None:
    """This method is deprecated. Please switch to Start."""
    ...

def AddKey(builder, key): # -> None:
    ...

def KeyValueAddKey(builder, key): # -> None:
    """This method is deprecated. Please switch to AddKey."""
    ...

def AddValue(builder, value): # -> None:
    ...

def KeyValueAddValue(builder, value): # -> None:
    """This method is deprecated. Please switch to AddValue."""
    ...

def End(builder):
    ...

def KeyValueEnd(builder):
    """This method is deprecated. Please switch to End."""
    ...

