"""
This type stub file was generated by pyright.
"""

np = ...
class TrtTable:
    __slots__ = ...
    @classmethod
    def GetRootAs(cls, buf, offset=...): # -> TrtTable:
        ...
    
    @classmethod
    def GetRootAsTrtTable(cls, buf, offset=...): # -> TrtTable:
        """This method is deprecated. Please switch to GetRootAs."""
        ...
    
    def Init(self, buf, pos): # -> None:
        ...
    
    def Dict(self, j): # -> KeyValue | None:
        ...
    
    def DictLength(self): # -> Any | Literal[0]:
        ...
    
    def DictIsNone(self):
        ...
    


def Start(builder): # -> None:
    ...

def TrtTableStart(builder): # -> None:
    """This method is deprecated. Please switch to Start."""
    ...

def AddDict(builder, dict): # -> None:
    ...

def TrtTableAddDict(builder, dict): # -> None:
    """This method is deprecated. Please switch to AddDict."""
    ...

def StartDictVector(builder, numElems):
    ...

def TrtTableStartDictVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    ...

def End(builder):
    ...

def TrtTableEnd(builder):
    """This method is deprecated. Please switch to End."""
    ...

