"""
This type stub file was generated by pyright.
"""

import platform
from .onnxruntime_pybind11_state import *

"""
Ensure that dependencies are available and then load the extension module.
"""
if platform.system() == "Windows":
    ...
