# ruff: noqa
# sourcery skip
# type: ignore
"""This type stub file was generated by pyright."""

from ._common import *
from ._constant import *
from ._enum import *
from ._tuple import *

"""Python Advanced Enumerations & NameTuples"""
version = ...
__all__ = [
    "CONFORM",
    "EJECT",
    "KEEP",
    "STRICT",
    "AddValue",
    "AddValueEnum",
    "AutoNumberEnum",
    "Constant",
    "Enum",
    "Flag",
    "FlagBoundary",
    "IntEnum",
    "IntFlag",
    "LowerStrEnum",
    "MagicValue",
    "Member",
    "MultiValue",
    "MultiValueEnum",
    "NamedConstant",
    "NamedTuple",
    "NoAlias",
    "NoAliasEnum",
    "NonMember",
    "OrderedEnum",
    "ReprEnum",
    "SqliteEnum",
    "StrEnum",
    "Unique",
    "UniqueEnum",
    "UpperStrEnum",
    "_reduce_ex_by_name",
    "add_stdlib_integration",
    "bin",
    "constant",
    "enum",
    "enum_property",
    "extend_enum",
    "member",
    "no_arg",
    "nonmember",
    "property",
    "remove_stdlib_integration",
    "skip",
    "unique",
]
if sqlite3 is None: ...
if PY2: ...
