# ruff: noqa
# sourcery skip
# type: ignore
"""This type stub file was generated by pyright."""

__all__ = ["getargspec", "raise_from_none", "raise_with_traceback"]

def getargspec(method):  # -> tuple[list[str], str | None, str | None, tuple[Any, ...] | None]:
    ...
def raise_with_traceback(exc, tb): ...
def raise_from_none(exc): ...
