# ruff: noqa
# sourcery: skip
# type: ignore
"""This type stub file was generated by pyright."""

from dataclasses import dataclass
from unittest import TestCase

from . import Enum

class TestEnumV37(TestCase):
    def test_repr_with_dataclass(self) -> None:  # -> None:
        @dataclass(repr=False)
        class Foo: ...

        class Entries(Foo, Enum): ...

        @dataclass
        class CreatureDataMixin: ...

        class Creature(CreatureDataMixin, Enum): ...
        class Huh: ...

        @dataclass(repr=False)
        class CreatureDataMixin(Huh): ...

        class Creature(CreatureDataMixin, Enum): ...

        @dataclass(repr=False)
        class CreatureDataMixin: ...

        class Creature(CreatureDataMixin, Enum): ...

if __name__ == "__main__": ...
