"""
This type stub file was generated by pyright.
"""

from onnx.backend.base import BackendRep

"""
Implements ONNX's backend API.
"""
class OnnxRuntimeBackendRep(BackendRep):
    """
    Computes the prediction for a pipeline converted into
    an :class:`onnxruntime.InferenceSession` node.
    """
    def __init__(self, session) -> None:
        """
        :param session: :class:`onnxruntime.InferenceSession`
        """
        ...
    
    def run(self, inputs: Any, **kwargs: Any) -> Tuple[Any, ...]:
        """
        Computes the prediction.
        See :meth:`onnxruntime.InferenceSession.run`.
        """
        ...
    


